### ISSUE TITLE
svg-icon

### ISSUE THREAD

**Issue by edenvidal** [rnbwdev/raincons#9]
# svg-icon issues
- [x] when switching `body data-theme="..."` then <svg-icon> don't know that colors have changed. therefore - is there a way to pass the color into the SVG in a persistent way?
- [x] When using, for example, `<svg-icon size="24">actions/plus</svg-icon>` in different contexts, there's no height defined so that it can stretch or shrink according to its parent. Solution: enforce height pretty much as it's enforcing width or use `display: flex;`
- [x] performance - how do we optimize the <svg-icon> to load first, and fast?
- [x] when loading, it shows the icon's name since it's its content - let's hide it?
- [x] external source

i consider simplifying <svg-icon> by converting it to a plain script that will go and find within the scope any `<img>` element with `href=".../*.svg"` or maybe an `id="svgicon"`. and then apply the coloring magic to it.
if we use `<img>`, then we gonna use urls anyway, and maybe should consider using raincons from a cdn, stored at https://raincons.rnbw.dev/icon.svg, this way it will be fetched from one source of truth. @sbsoso0411 wdyt?

# raincons
- [x] create all of the missing icons
- [x] fill them in the jumpstart/actions
- [x] let's get a cdn for raincons, and then set the source of svg-icon in rnbw to somehow fetch icons from there? @sbsoso0411 

# svg-icon-template
- [x] simplify
- [x] get `icons.js` and its pair `index.html` outside the `/icons` folder.
  - [x] edit `icons.js` to work with that.
- [x] rename `index.html` to `icons.html`

**Comment by sbsoso0411** [comment]
@edenvidal 
I fully understood the svg-icon issues.
All of them are also the ones I could face during development.
And now sure! I believe that we can fix all of the issues.

Also, regarding the `building plain script`, that's really nice.
That would be even better than the current svg-icon web component, since you don't need any `raincons` resource in the project.
And not sure yet, but it would bring some more advantages I guess.. 😄

**Comment by edenvidal** [comment]
@sbsoso0411 sounds good. i vouch for simplifying svg-icon to work as an enhancement for <img> objects to pass color data into `.svg` files. let's keep this task in order and get back to it soon

**Comment by edenvidal** [comment]
@sbsoso0411 i'm setting this higher in the priority as many things related to it, and i don't wanna make too much debt. (need to convert all `<svg-icon>` to `<img>`)

**Comment by edenvidal** [comment]
@sbsoso0411 so, the following todo's refer to the <svg-icon> before we made a lot of changes to it.

- [ ] keep <svg-icon> as a web component (yay).
- [ ] keep the functionality that keeps the color in sync with its inheritance in a persistent way. for the case of when there's a change in `body data-theme="..."` or any other kind of live css event.
- [ ] allow in`svg-icon.config.json` to place external source (cdn). for example:`"src": "https://raincons.rnbw.dev/icons/",`
- [ ] get rid of the "color" property, so that the only enforcement of colors will be through css. if someone (or us) wanna change the color, they can do it through css like <svg-icon style="color:#123456"></svg-icon>
- [ ] get rid of the "size" property. so that sizes are defined naturally by the svg source file or by css.

in general, we're letting <svg-icon> focusing on what it does best which is making sure colors are in sync with the styling mechanism + simple dev experience to use. 🙌
-

- [ ]  performance - how do we optimize the to load first, and fast?
- [ ]  when loading, it shows the icon's name since it's its content - let's hide it?

**Comment by sbsoso0411** [comment]
@edenvidal 
please let me know the `code` for `svg-icon` web component.
something like
```<svg-icon>icon-name</svg-icon>```

there will be no `color` and no `size` property, but we will have only the external source `url` in `svg-icon.config.json`.
I think it would be enough then. what do you think?

**Comment by edenvidal** [comment]
@sbsoso0411 yes. if there's a configured source, it would be `<svg-icon>name</svg-icon>`. if not then `<svg-icon src="..."></svg-icon>`
